apiVersion: v2
name: grafana
description: Wrapper chart for kube-prometheus-stack
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 58.2.1
    repository: https://prometheus-community.github.io/helm-charts
